In [4]:
import numpy as np

matriz1=np.array([[3,2,1],[2,1,4],[4,1,3]])

print(matriz1)

suma_matriz1=np.sum(matriz1)

print("La suma de los elementos es: ", suma_matriz1)

[[3 2 1]
 [2 1 4]
 [4 1 3]]
La suma de los elementos es:  21
